# Generated by Django 3.1.7 on 2021-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cart_cartplant_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
