# Generated by Django 3.1.7 on 2021-03-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_plant_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('flower', 'flower'), ('fruit', 'fruit'), ('seed', 'seed')], max_length=20),
        ),
    ]
