# Generated by Django 3.1.7 on 2021-03-27 19:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210328_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
